---
title: Simulation Settings
---

```{r}
library(otm)
library(tidyverse)
library(patchwork)
```

# OTM

```{r}
df <- otm:::generate_otm_data(cutpoints = c(2.7, 3.3, 3.8, 6.2, 9.9, 12.6, 19.1),
                             beta_yprev = c(0, 3.7, 4.8, 7.7, 11.1, 15.5),
                             beta_t = -0.01,
                             beta_tx = 0,
                             beta_t_tx = -0.02,
                             tx_end = 28,
                             baseline_y = 5,
                             times = 1:28,
                             tx_type = "linear",
                             absorb = 8L,
                             n_subjects = 1e4)
```

```{r}
otm:::plot_empirical_sops(df, type = 1, absorb = 8L, tmax = 28)
```

```{r}
otm:::plot_empirical_sops(df, type = 2, absorb = 8L, tmax = 28)
```

```{r}
otm:::plot_empirical_sops(df, type = 3, absorb = 8L, tmax = 28)
```

```{r}
otm:::plot_spearman_corr(df, absorb = 8L, tmax = 28L)
```

# Mixed Effects

```{r}
df <-
  otm:::generate_ordinal_random_effects_data(
        cutpoints = c(-5, -3, -2, 0, 1, 2, 4),
        beta_t = -0.1,
        beta_tx = -0.2,
        beta_t_tx = -0.0,
        times = 1:28,
        rand_intercept_sd = 1,
        rand_slope_sd = 0.05,
        rand_eff_corr = 0,
        n_subjects = 1e4
      )

otm:::plot_empirical_sops(df, type = 1, absorb = 999L, tmax = 28)
otm:::plot_empirical_sops(df, type = 4, absorb = 999L, tmax = 28)
otm:::plot_spearman_corr(df, absorb = 999L, tmax = 28L)
```


```{r}
otm:::fit_otm_rand_eff(df, 0, TRUE)
```



