---
title: "Simulation Testing"
author: "Max Rohde"
---

```{r}
i <- 1

load_all()

suppressMessages(library(dplyr))
suppressMessages(library(purrr))
suppressMessages(library(survival))
suppressMessages(library(glue))
suppressMessages(library(VGAM))
suppressMessages(library(rms))

# Number of iterations to compute power
ITER <- 20

# 2688
# Create parameter settings
GRID_sample_size <- c(200, 300)
GRID_baseline_y <- c(4L, 5L, 6L, 7L)
GRID_cutpoints <- list(c(2.7, 3.3, 3.8, 6.2, 9.9, 12.6, 19.1))
GRID_beta_yprev <- list(c(0.006, 3.7, 4.8, 7.7, 11.1, 15.5))
GRID_beta_t <- c(0, -0.02)
GRID_beta_tx <- c(0, -0.2)
GRID_beta_t_tx <- c(-0.005, -0.01, -0.02)
GRID_tx_end <- seq(2, 28, 2)

GRID_knots <- c(3, 6)
tx_type <- "linear"

param_df <-
  tidyr::crossing(
    GRID_sample_size,
    GRID_baseline_y,
    GRID_cutpoints,
    GRID_beta_yprev,
    GRID_beta_t,
    GRID_beta_tx,
    GRID_beta_t_tx,
    GRID_tx_end,
    GRID_knots)

row <- param_df[i,]

################# Job specific settings ########################################

# Use different sample size based on the job array
n_subjects <- row$GRID_sample_size[[1]]

# OTM true parameters

cutpoints <- row$GRID_cutpoints[[1]]
beta_yprev <- row$GRID_beta_yprev[[1]]
beta_t <- row$GRID_beta_t[[1]]
beta_tx <- row$GRID_beta_tx[[1]]
beta_t_tx <- row$GRID_beta_t_tx[[1]]
baseline_y <- row$GRID_baseline_y[[1]]
tx_end <- row$GRID_tx_end[[1]]
knots <- row$GRID_knots[[1]]
```

```{r}
  times <- 1L:28L
  tmax <- max(times)
  death_state <- 8L
  recovery_states <- c(1L, 2L, 3L)

  # Generate dataset
  df <- otm:::generate_dataset(cutpoints = cutpoints,
                         beta_yprev = beta_yprev,
                         beta_t = beta_t,
                         beta_tx = beta_tx,
                         beta_t_tx = beta_t_tx,
                         tx_end = tx_end,
                         baseline_y = baseline_y,
                         times = times,
                         tx_type = tx_type,
                         absorb = 8,
                         n_subjects = n_subjects)


  # Create the survival data frame
  surv_df <- create_survival(df,
                             tmax = tmax,
                             death_state = death_state,
                             recovery_states = recovery_states)

  # Merge in tx information
  surv_df <-
    df |>
    filter(t == 1) |>
    select(id, tx) |>
    right_join(surv_df, by = "id")

```


```{r}
fit_otm(df, 6)
```

```{r}
fit_cox(surv_df, type = "prop_hazard")
```



