---
title: Simulation Settings
---

```{r}
library(otm)
library(tidyverse)
library(patchwork)
```

```{r}
samp_size <- 1e4
```

# OTM

```{r}
baseline_y <-
      list(states = c(4,5,6,7),
           proportions = c(0.25, 0.25, 0.25, 0.25))

df <- otm:::generate_otm_data(cutpoints = c(2.7, 3.3, 3.8, 6.2, 9.9, 12.6, 19.1),
                             beta_yprev = c(0, 3.7, 4.8, 7.7, 11.1, 15.5),
                             beta_t = -0.01,
                             beta_tx = 0,
                             beta_t_tx = -0.02,
                             tx_end = 28,
                             baseline_y = baseline_y,
                             times = 1:28,
                             tx_type = "linear",
                             absorb = 8L,
                             n_subjects = samp_size)
```

```{r}
f1 <- otm:::plot_empirical_sops(df, type = 1, absorb = 8L, tmax = 28)
```

```{r}
f1_facet <-
f1 +
  coord_cartesian() +
  facet_wrap(~y, scales = "free_y") +
  scale_x_continuous(breaks = c(1,3,7,14,21,28))
```

```{r}
f1_comb <- 
  (f1 / f1_facet) +
  plot_layout(guides = "collect")
```

```{r}
ggsave(
  filename = "otm_illustration.png", 
  plot = f1_comb,
  bg = "white",
  device = ragg::agg_png,
  units="in",
  height = 7,
  width = 7,
  dpi = 600,
  scale = 1)
```

```{r}
otm_corr <-
  otm:::plot_spearman_corr(df, absorb = 8L, tmax = 28) +
  labs(title = "Ordinal transition model")
```

# Mixed Effects

```{r}
df <-
  otm:::generate_ordinal_random_effects_data(
        cutpoints = c(-5, -3, -2, 0, 1, 2, 4),
        beta_t = -0.1,
        beta_tx = -0,
        beta_t_tx = -0.1,
        times = 1:28,
        rand_intercept_sd = 1,
        rand_slope_sd = 0.0001,
        rand_eff_corr = 0,
        n_subjects = samp_size
      )
```


```{r}
f1 <- otm:::plot_empirical_sops(df, type = 1, absorb = 999L, tmax = 28)
```

```{r}
f1_facet <-
f1 +
  coord_cartesian() +
  facet_wrap(~y, scales = "free_y") +
  scale_x_continuous(breaks = c(1,3,7,14,21,28))
```

```{r}
f1_comb <- 
  (f1 / f1_facet) +
  plot_layout(guides = "collect")
```

```{r}
ggsave(
  filename = "mixed_eff_illustration.png", 
  plot = f1_comb,
  bg = "white",
  device = ragg::agg_png,
  units="in",
  height = 7,
  width = 7,
  dpi = 600,
  scale = 1)
```

```{r}
randeff_corr <-
  otm:::plot_spearman_corr(df, absorb = 999L, tmax = 28) +
  labs(title = "Random intercept model") +
  coord_equal()
```

# Correlation

```{r}
corr <-
(otm_corr + randeff_corr) +
plot_layout(guides = "collect")
```

```{r}
ggsave(
  filename = "corr_illustration.png", 
  plot = corr,
  bg = "white",
  device = ragg::agg_png,
  units="in",
  height = 5,
  width = 7,
  dpi = 600,
  scale = 1.8)
```

```{r}
together <-
  otm_corr + randeff_corr
```


