# Declare variables for use in ggplot2
utils::globalVariables(c("sop", "day", "y"))

generate_barplot <- function(sop_dataframe){
  sop_dataframe |>
    ggplot2::ggplot() +
    ggplot2::aes(x = day, y = sop, fill = y) +
    ggplot2::geom_col(position="fill") +
    ggplot2::scale_x_continuous(breaks = 1:28) +
    ggplot2::scale_y_continuous(breaks = seq(0, 1, 0.1)) +
    ggplot2::scale_fill_brewer(palette = "YlOrRd") +
    ggplot2::labs(x = "Study Day",
         y = "SOP",
         fill = "State") +
    cowplot::theme_cowplot(font_size = 11)
}

generate_lineplot <- function(sop_dataframe){
  sop_dataframe |>
    ggplot2::ggplot() +
    ggplot2::aes(x = day, y = sop, color=y) +
    ggplot2::geom_line() +
    ggplot2::geom_point(alpha=0.6, size=1.5) +
    ggplot2::scale_x_continuous(breaks = 1:28) +
    ggplot2::scale_color_brewer(palette = "Dark2") +
    ggplot2::scale_y_continuous(breaks = seq(0, 1, by=0.1)) +
    ggplot2::coord_cartesian(ylim = c(0,1)) +
    ggplot2::labs(x = "Study Day",
         y = "SOP",
         color = "State") +
    cowplot::theme_minimal_hgrid(font_size = 11)
}

#' Plot the SOPs implied by the OTM parameters
#'
#' @param sop_dataframe A SOP data.frame generated by otm::compute_sop()
#' @param type Use "bar", "line", or "both" for the plot
#' @return SOP plot using ggplot2
#' @export
generate_sop_plot <- function(sop_dataframe,
                              type = "both"){

  # Make sure `y` is a factor
  if (!is.factor(sop_dataframe$y)) {
    sop_dataframe$y <- as.factor(sop_dataframe$y)
  }

  if (!(type %in% c("both", "bar", "line"))) {
    stop("type must be one of (both, bar, line)")
  }

  if (type == "both") {
    bar <- generate_barplot(sop_dataframe)
    line <- generate_lineplot(sop_dataframe)

    out <-
      patchwork::wrap_plots(
        bar,
        line,
        ncol = 1
      )
  }

  if (type == "line") {
    out <- generate_lineplot(sop_dataframe)
  }

  if (type == "bar") {
    out <- generate_barplot(sop_dataframe)
  }

  return(out)
}
