# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
compute_transition_probabilitiesC <- function(params, yprev, day, covariates) {
    .Call(`_otm_compute_transition_probabilitiesC`, params, yprev, day, covariates)
}

#' @export
generate_datasetC <- function(params, covariates, baseline_y, times, absorb, n_subjects) {
    .Call(`_otm_generate_datasetC`, params, covariates, baseline_y, times, absorb, n_subjects)
}

